spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: currency-exchange
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


