spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: currency-exchange
server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka